### ISSUE TITLE
When a new release?

### ISSUE THREAD

**Issue by nunotexbsd** [astrand/xclip#106]
Hello,

I use xclip for some years and I'm asking why not a new release since there is so much code activity?

Thanks,

Nuno Teixeira

**Comment by hackerb9** [comment]
"Much code activity," even when the bulk is bug fixes, means more testing time to make sure it is correct. 

After pull #88 gets merged, I'll mark a checkpoint and ask @astrand what he thinks about a release. While I'm eager for a release - there are bug fixes and enhancements I'm holding off working on - I lean towards taking it slow. I wouldn't want to release something embarrassing and have to wear a paper bag over my head so people won't recognize me. 😜

**Comment by nunotexbsd** [comment]
Thank you for quick answer.
