### ISSUE TITLE
Big files problem

### ISSUE THREAD

**Issue by mcnuggetsx20** [astrand/xclip#136]
Xclip has a problem with copying and pasting files bigger than 1 MB. This happens to me when I try to copy and paste a `.png` file. The program I paste the image to just freezes. I know there is a closed issue about it, with people claiming the problem was fixed, but it still occurs.

**Comment by mil-ad** [comment]
There hasn't been a release since the fix went it. If you're on Arch you can use `xclip-git` AUR package to install the latest code.
