### ISSUE TITLE
xclip in a docker container authorization error

### ISSUE THREAD

**Issue by bwintertkb** [astrand/xclip#141]
Hi all,

Thank you for reading this!

I'm building a dev environment in a Docker container from the image `ubuntu:20.04` and within that image I run the command `RUN sudo apt-get -y install xclip`. Unfortunately when I invoke xclip I get the following error:
`Authorization required, but no authorization protocol specified Error: Can't open display: :1`

Do you know what this might mean? And also how to go about solving it?

Thanks in advance!

**Comment by hackerb9** [comment]
Are you able to run any X programs? For example, `xeyes` or `xdpyinfo`?

**Comment by quartzjer** [comment]
Thanks @bwintertkb, xclip will only work in a functioning X11 environment where it can connect to the X server via the DISPLAY.
