### ISSUE TITLE
Migration to GitHub is not complete

### ISSUE THREAD

**Issue by Neustradamus** [astrand/xclip#145]
Dear @astrand,

Can you add a "move" box like https://sourceforge.net/projects/handbrake for example.
- https://sourceforge.net/p/xclip/

To disable/delete tabs, go here: https://sourceforge.net/projects/xclip/
To add a new tab, go here: https://sourceforge.net/projects/xclip/
To change informations, go here: https://sourceforge.net/p/xclip/admin/overview
To export, go here: https://sourceforge.net/p/xclip/admin/export

The new place can be added in:
- "Moved Project to", here: https://sourceforge.net/p/xclip/admin/overview
- A new tab, go here: https://sourceforge.net/projects/xclip/

Thanks in advance.

**Comment by quartzjer** [comment]
:wave: @Neustradamus ;)

I'm helping @astrand with maintenance of xclip and I believe all we're going to get is the current moved message that is already on the old sourceforge project page.

**Comment by Neustradamus** [comment]
@quartzjer: Nice! :)

But can you reopen this ticket?
The request is not solved.

The "moved box" has not been added and it is always here:
- https://sourceforge.net/p/xclip/code/
- https://sourceforge.net/p/xclip/_list/tickets

In more, can you see to be admin of Sourceforge project?

In more other points, @astrand must to connect to add you admin in the team:
- https://sourceforge.net/p/xclip/_members/

**Comment by Neustradamus** [comment]
@astrand: Can you add Jeremie in the Sourceforge project?

Thanks in advance.
