### ISSUE TITLE
Error on macOS Ventura

### ISSUE THREAD

**Issue by sanderverschoor** [astrand/xclip#147]
```
xclip  ~/.ssh/id_rsa.pub     
Error: Can't open display: (null)

```
Am i doing something wrong?

**Comment by dpeterc** [comment]
It appears as if you don't have XQuartz installed or configured properly.
Do other stock x11 programs like "xclock" work?

**Comment by quartzjer** [comment]
Please re-open if this is still an issue, thanks!
