### ISSUE TITLE
xclip does not set X11 clipboard

### ISSUE THREAD

**Issue by astrand** [astrand/xclip#15]
This works and prints 'hello':
$ echo hello | xclip
$ xclip -o
hello

Pasting in a graphical application doesn't work. Here I get the old content, before 'hello' was copied the way shown above.
But it works the other way around. A text copied from a website can be printed out on a console properly using 'xclip' command.

Can anyone confirm this?

Thanks,
Andreas

Reported by: *anonymous

Original Ticket: [xclip/bugs/4](https://sourceforge.net/p/xclip/bugs/4)

**Comment by hackerb9** [comment]
I'm closing this bug as '-selection clipboard' seems like the solution. Note that once pull request #88 is merged users can simply use "-c".
