### ISSUE TITLE
WebP images that have been inserted to the clipboard using xclip can't be pasted into other programs

### ISSUE THREAD

**Issue by rodrigomorales1** [astrand/xclip#151]
# Steps to reproduce

1.  Insert a WebP image to the clipboard using `$ xclip -selection clipboard -t image/webp /tmp/a.webp`. You can download a simple image from Wikimedia Commons using the following command: `$ wget -O /tmp/a.webp 'https://upload.wikimedia.org/wikipedia/commons/c/c6/Vunosnii-balcon.webp'`
2.  Open any of the following programs: Inkscape, GIMP, LibreOffice
3.  Try pressing `Ctrl+v` to insert the WebP image in the program

# What happened?

Although the image is in the clipboard, pressing `Ctrl+v` doesn't paste the image in the program (be it Inkscape, GIMP or LibreOffice)

# What should have happened?

Upon pressing `Ctrl+v`, the image should have been pasted into the program.

# Additional information

When I open [the image](https://upload.wikimedia.org/wikipedia/commons/c/c6/Vunosnii-balcon.webp) in Mozilla Firefox 125.0.3 and I right click on the image and I choose the option `Copy Image`, I can then paste it in any of the aforementioned programs: Inkscape, GIMP and LibreOffice. The image can't be pasted into those programs when the image has been inserted to the clipboard using `$ xclip -selection clipboard -t image/webp /tmp/a.webp`.

# System information

-   Operating system: Ubuntu 22.04.4 LTS
-   xclip version: 0.13
-   inkscape version: Inkscape 1.3.2 (1:1.3.2+202311252150+091e20ef0f)
-   gimp version: GNU Image Manipulation Program version 2.10.30
-   libreoffice version: LibreOffice 7.3.7.2 30(Build:2)

**Comment by schrmh** [comment]
Try `xclip -selection clipboard -t image/webp -i /tmp/a.webp` (with -i)

Honestly, I was originally speculating about if common terminal emulators doesn't provide a selection target for images but after clearing by using
`xclip -selection clipboard /dev/null`
I was able to also use the command you tried and paste the image into another application then.
So maybe we just copied something before / something took priority over image targets. (Before using -i I also tried it with other image files, so this is not webp specific.)
Well, now I get
```
TARGETS
image/webp
```
when checking targets via `xclip -selection clipboard -t TARGETS`.

**Comment by quartzjer** [comment]
This is unfortunately due to the target applications not supporting the image/webp type from the clipboard, most linux apps copy and paste images via image/png.

**Comment by vitaly-zdanevich** [comment]
> target applications not supporting the image/webp type from the clipboard

Including Gimp?

**Comment by vitaly-zdanevich** [comment]
Created bug for Firefox https://bugzilla.mozilla.org/show_bug.cgi?id=1939783

**Comment by vitaly-zdanevich** [comment]
My workaround: replace `image/webp` to `image/png`: it works for Github, Evernote - in Firefox, Gentoo Linux, see this webp:

![image](https://github.com/user-attachments/assets/729acdab-24b9-4830-91f9-c10a45a14b7f)
