### ISSUE TITLE
xclip via SSH

### ISSUE THREAD

**Issue by MemoKazim** [astrand/xclip#152]
When I try to use xclip command via SSH connection it gives following error:

![Screenshot 2024-06-03 165302](https://github.com/astrand/xclip/assets/116759655/289b9526-cc02-471c-bb12-3dce55e8e4ad)

I managed to avoid from this error by exporting DISLPAY properth in zsh:

![image](https://github.com/astrand/xclip/assets/116759655/a4e1d4af-495e-48d4-a5b9-82d83bd0f151)

But it seems it only works host itself and `xclip` could not send clipboard to remote session which connected via SSH

**Comment by quartzjer** [comment]
This is due to the architecture of X11, it's not something xclip can natively support unfortunately.
