### ISSUE TITLE
xclip using wrong clipboard

### ISSUE THREAD

**Issue by bwanaaa** [astrand/xclip#26]
in gedit, copy some text
go to terminal and type
`ls -la | xclip`

go back to gedit
then middle click -> get what xclip copied
ctrl+v in gedit -> get whatever you copied initially

go back to terminal
then middle click -> get what xclip copied
ctrl+v in gedit -> get whatever you copied initially

how can i get xclip to be consistent about putting whatever it copies into the same clipboard as gedit?

**Comment by astrand** [comment]
Use xclip -selection clipboard.
