### ISSUE TITLE
Release 0.13

### ISSUE THREAD

**Issue by Nowaker** [astrand/xclip#27]
Many distributions (e.g. OpenSuse) still use a prehistoric version 0.12 and lack access to many useful features released after 2007, for example support for `-t image/png`. (https://github.com/hwangcc23/xclip/commit/d7e6f233c24346b8a1a8a8ccde72fa0bc1cf2a68)

Please release current code as 0.13 so everyone gets access to the recent features. It's been simply too long since the previous release.

**Comment by hishamhm** [comment]
I second this request! A simple 
```
git tag v0.13
git push --tags
```
would do wonders to get updated releases out there! :)

**Comment by astrand** [comment]
I haven't forgotten about you, just been very busy. Will look at this in a near future.

**Comment by astrand** [comment]
I've created a release now, please check.

**Comment by Nowaker** [comment]
Thanks @astrand! Almost every Linux user ows you a beer.

**Comment by hishamhm** [comment]
Thank you! It's much appreciated! :)

**Comment by whnr** [comment]
I hope you don't mind my dumb question: But how can we make the .13 release available in standard package managers? It would be great to just get it via `apt upgrade`

**Comment by Nowaker** [comment]
@whnr After an author releases a stable version, distro package maintainers will release a newer package sooner or later. Depending on Linux distro, it may be just days (Arch Linux, Gentoo) or years (Debian, Ubuntu).

Closing the ticket since the author released 0.13 a year ago. :)
