### ISSUE TITLE
-rmlastnl option affects -filter output

### ISSUE THREAD

**Issue by GrumpyDave** [astrand/xclip#36]
According to the man page the -filter option should send stdin back to stdout unmodified.  When the -rmlastnl option is enabled the data written to stdout is missing that last newline.

As a workaround I'm using sed to add a newline to the last line after xclip in a pipeline but this had the undesired effect of adding a newline even when there wasn't one there in the first place.

Addionally I noticed the -filter option is not shown on the "xclip -help" output.

**Comment by hackerb9** [comment]
Thank you, @GrumpyDave. Sorry for the long delay. I believe your bug is now fixed.
