### ISSUE TITLE
Image with lower part black on Ubuntu

### ISSUE THREAD

**Issue by pabloab** [astrand/xclip#37]
On Ubuntu 16.04.3 LTS I was happily using this alias for several years now: ``alias clipboard2photo='xclip -selection clipboard -t image/png -o > "`date +%Y-%m-%d_%T`.png"'`` to paste on terminal an image captured with <kbd>Ctrl+Shift+PrintScreen</kbd>,
Somehow now with xclip v0.12+svn84-4 (or maybe a conflict with other updated package) I experience a strange behavior:
Without `-verbose` the command **sometimes** generate an image correctly on the upper part of the image and all black in the lower part. No patter found:
- On image 1029px hight only upper 331px (~32%) were right.
- On image 825px hight only upper 296px (~36%) were right.
other times just:
```
Error: target image/png not available
```
With -verbose xclip send not output and **sometimes** return
```
Connected to X server.
Using selection: XA_CLIPBOARD
Using image/png.
X Error of failed request:  BadAtom (invalid Atom parameter)
  Major opcode of failed request:  17 (X_GetAtomName)
  Atom id in failed request:  0x0
  Serial number of failed request:  22
  Current serial number in output stream:  22
```
other times:
```
Connected to X server.
Using selection: XA_CLIPBOARD
Using image/png.
Type is image/png.
```
I know the odd _sometimes_ but I couldn't find a pattern. Doesn't seem related to the size of the captured image.

**Comment by astrand** [comment]
Thanks for the report. Does it work correctly if pasting into, say, Gimp instead?

**Comment by pabloab** [comment]
Yes, pasting on Gimp works fine, that was the first thing I tried.

**Comment by astrand** [comment]
The reason why -verbose fails is probably because it is running:
    if (fverb == OVERBOSE) {	/* print in verbose mode only */
	char *atom_name = XGetAtomName(dpy, sel_type);
	fprintf(stderr, "Type is %s.\n", atom_name);
	XFree(atom_name);
    }
And some some reason, XGetAtomName fails. My guess is that the clipboard is changing while xclip is running. Are you running some kind of clipboard manager? KDE/klipper?

**Comment by pabloab** [comment]
Not using any clipboard manager.

I create and tried [this script to simulate my movements](https://gist.github.com/pabloab/bb01c67ee35b661fc215543104401587). Fist runs give 0 Bytes and _identify: improper image header_ for captures up to 100x100. Then always get all 6 files with almost same size (~12KB, 100x100). It seems `xclip` remember last runs.

Feel free to improve that script to simulate more time sleeps and capture sizes I could send you the output.

**Comment by astrand** [comment]
Unfortunately I don't have a Ubuntu 16.04 machine to test with right now. 

Have you tried other targets ie image types? Perhaps there's some problem with the Ubuntu screen capture software which only affects PNG. Gimp might use some other target.

**Comment by pabloab** [comment]
Maybe you could use VirtualBox. I [improved the script](https://gist.github.com/pabloab/bb01c67ee35b661fc215543104401587) to switch to image/jpeg. Same problem. At first 0 Bytes, then only 100x100.

**Comment by hackerb9** [comment]
@astrand While the weirdness with the target not being available does sound like a clipboard manager problem, it could be the 1MB bug I fixed in my patches. Using my latest changes, 'xclip -debug' will show the name of who owns the selection so we can more easily see if there's clipboard manager interfering.

**Comment by pabloab** [comment]
I use the `clipboard2photo` alias regularly and I didn't have this issue anymore, in years. Now using Ubuntu 18.04, Gnome 3.28.4, xclip 0.12+svn84-4build1. I don't remember using any clipboard manager at that time.

I now tried to reproduce it based on @hackerb9 hypotheses, capturing a big screenshot, more than 3 MB. Now works as expected, I couldn't reproduce it.

As far as I'm concerned this issue could be closed.

**Comment by hackerb9** [comment]
@pabloab Thank you for taking the time to retest it. Let us know if you have any other issues.
