### ISSUE TITLE
Xclip never quits

### ISSUE THREAD

**Issue by quilicicf** [astrand/xclip#45]
Hi, 

First of all, thanks for xclip, it's a very handy tool.

I'd like to report a bug though that prevents me from using it from NodeJS.
Basically, xclip never properly exits. It's been tested on macos and ubuntu.

## Xclip version

Well, `xclip --version` doesn't return anything so I used the command below.

```
> apt-cache policy xclip
xclip:
  Installed: 0.12+svn84-4build1
  Candidate: 0.12+svn84-4build1
  Version table:
 *** 0.12+svn84-4build1 500
        500 http://fr.archive.ubuntu.com/ubuntu artful/main amd64 Packages
        100 /var/lib/dpkg/status
```

## How to reproduce

```shell
echo ok | xclip -sel clipboard
ps -ef | grep xclip
```

Output: 

```shell
cyp       1908     1  0 14:31 pts/1    00:00:00 xclip -sel clipboard # <- I did not expect xclip to be still running
cyp       1925  1305  0 14:31 pts/1    00:00:00 grep --color=auto xclip
```

## Original ticket

I first thought this might be a NodeJS issue. You can find the original discussion [here](https://github.com/nodejs/help/issues/1124#issuecomment-370409898).

Thanks for helping!

**Comment by astrand** [comment]
This is by design. xclip needs to be running, so that other applications can request the clipboard data. See also the -l argument:

       -l, -loops
              number of X selection requests (pastes into X applications) to wait for before exiting, with a value of 0 (default) causing xclip to wait for an unlimited number of requests until another application (possibly another  invocation  of  xclip)  takes ownership of the selection

**Comment by quilicicf** [comment]
Works better with `echo ok | xclip -sel clipboard -l 1` indeed. 
I overlooked that parameter in the docs, didn't expect `loops` to have something to do with exiting.
Maybe that's only me though. 
Thanks for helping out.
