### ISSUE TITLE
Help me with the definitive guide to build it on Msys/Mingw64

### ISSUE THREAD

**Issue by abdulbadii** [astrand/xclip#54]
I have tried none to build/install it on Msys/Mingw64, but same error when configuring in either Msys or mingw64 window:

...
checking X11/Xmu/Atoms.h usability... no
checking X11/Xmu/Atoms.h presence... no
checking for X11/Xmu/Atoms.h... no
configure: error: *** X11/Xmu/Atoms.h is missing ***

would anyone give me to the definitive guide  building one... ?

**Comment by astrand** [comment]
xclip is not a Windows application, so it does not make sense to try to build it in a Windows build environment.
