### ISSUE TITLE
xclip no longer exits when it loses the selection

### ISSUE THREAD

**Issue by hackerb9** [astrand/xclip#64]
Hi!

xclip forks into the background and never exits. This was caused by a commit on July 17th (see below). You can test it like so:

```
echo "Testing whether xclip exits correctly when the selection is lost."
echo hello | ./xclip -verbose -i >/dev/null 2>&1 &
sleep 1
echo goodbye | ./xclip -i
sleep 1
if ps $! >/dev/null; then 
  echo "FAIL: Zombie xclip yet lives! Killing."
  pkill xclip
else
  echo "PASS: xclip exited correctly after losing selection."
fi
```

The first xclip process should exit when the second takes the selection, but it does not. I suggest that the above test should be put at the beginning of `xctest` (before it creates dozens of undying xclip processes). 

6623ccd9e5c6c573c4a58b60fac80896e191344c is the first bad commit

In the commit before that, b161f2c5df3212ab18a2361e59d75d23a1efc676, xclip works correctly. 

Thanks.

**Comment by kennbr34** [comment]
The problem is with the nested loop at the end of doIn() and its attempt to be compliant with ICCM standards.  It tests if the selection has been cleared, and then states that ICCM dictates it complete the transfer for whatever client took ownership of it, and then continues back to the top of the nested loop.  However when it enters XNextEvent(), it seems to just hang at xcb_wait_for_event().

> Program received signal SIGINT, Interrupt.
> 0x00007ffff75a7bc4 in __GI___poll (fds=0x7fffffffdce8, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
> 29	../sysdeps/unix/sysv/linux/poll.c: No such file or directory.
> (gdb) where
> #0  0x00007ffff75a7bc4 in __GI___poll (fds=0x7fffffffdce8, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
> #1  0x00007ffff6dfb747 in ?? () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
> #2  0x00007ffff6dfd36a in xcb_wait_for_event () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
> #3  0x00007ffff78c23e8 in _XReadEvents () from /usr/lib/x86_64-linux-gnu/libX11.so.6
> #4  0x00007ffff78b1340 in XNextEvent () from /usr/lib/x86_64-linux-gnu/libX11.so.6
> #5  0x000055555555639f in doIn (progname=<optimized out>, win=<optimized out>) at xclip.c:406
> #6  main (argc=<optimized out>, argv=<optimized out>) at xclip.c:696

**Comment by hackerb9** [comment]
Closing bug: has been fixed.
