### ISSUE TITLE
Unable to empty clipboard on Ubuntu 19.10

### ISSUE THREAD

**Issue by miskovics** [astrand/xclip#81]
I understood by reading in several articles on the Internet, that the second and third lines would clear the clipboard, but for me, on my Ubuntu 19.10 machine they don't.

```bash
$ echo "TEST" | xclip -i -selection clipboard && xclip -o -selection clipboard
TEST
$ echo -n "" | xclip -i -selection clipboard && xclip -o -selection clipboard
TEST
$ echo -n | xclip -i -selection clipboard && xclip -o -selection clipboard
TEST
$ 
```

**Comment by hackerb9** [comment]
Weird. I pasted what you typed in and it worked for me. What version of xclip are you using?

**Comment by miskovics** [comment]
This is the current version I use, with the same phenomena.

```
$ xclip -version
xclip version 0.13
Copyright (C) 2001-2008 Kim Saunders et al.
Distributed under the terms of the GNU GPL
$
```

Nevertheless, following a sudden inspiration, I terminated Autokey, retested the use case and `xclip` works as expected.

```
$ echo "TEST" | xclip -i -selection clipboard && xclip -o -selection clipboard
TEST
$ echo -n | xclip -i -selection clipboard && xclip -o -selection clipboard
$ 
```

So it seems there is no issue with `xclip`, but Autokey somehow prevents `xclip` to do its work; closing the issue here.

**Comment by hackerb9** [comment]
Thanks for figuring out the mystery! Do you believe it is an issue in autokey itself, not your particular configuration? If so, it may be helpful to that project if you report a bug with them.

**Comment by miskovics** [comment]
It was my config.
