### ISSUE TITLE
the content copied by xclip only can be used in the terminal with shift+iinsert not same with copy by ctrl + c 

### ISSUE THREAD

**Issue by woshichuanqilz** [astrand/xclip#82]
xclip version 0.13
wm: i3
os: manjaro 20
shell: fish

Here is the thing. 

I run command `uptime | xclip` in the terminal.  The situation is: 
* I can paste the content just in the current terminal with shift+insert 
* I cant paste the content with ctrl + v, but if I copied something by ctrl + c I can use ctrl + v to paste them. 
* If you switch to other window, neither shift+insert nor ctrl + v will work.
* I use copyq which is a clipboard manager. Which cant see the content copied by xclip command. 

How to solve these problems?

**Comment by Kratacoa** [comment]
This is probably relevant to the terminal emulator you're using (which you didn't mention).

**Comment by woshichuanqilz** [comment]
> This is probably relevant to the terminal emulator you're using (which you didn't mention).

alacritty

**Comment by Kratacoa** [comment]
Sorry for the comment above, it's misguiding.  
You are using the PRIMARY clipboard, not the CLIPBOARD which is usually referred to by the keys you mentioned. To select the latter, add `-sel clipboard` as by the manpage.  
Reference: https://specifications.freedesktop.org/clipboards-spec/clipboards-latest.txt

**Comment by woshichuanqilz** [comment]
> Sorry for the comment above, it's misguiding.
> You are using the PRIMARY clipboard, not the CLIPBOARD which is usually referred to by the keys you mentioned. To select the latter, add `-sel clipboard` as by the manpage.
> Reference: https://specifications.freedesktop.org/clipboards-spec/clipboards-latest.txt

Thank you done.
