### ISSUE TITLE
./configure should work without needing autoconf first

### ISSUE THREAD

**Issue by hackerb9** [astrand/xclip#89]
If I remember correctly, projects are supposed to distribute the `configure` script with the source code so that people don't need to install autoconf in order to build the program.

**Comment by astrand** [comment]
Correct. configure should be in release tarballs (but not in Git).

**Comment by hackerb9** [comment]
Thanks. I hadn't known that it didn't belong in git, but I suppose it makes sense since it is a generated file. 

Is this something we can bend the rules on to make it easier for other people to build directly from git? That seems to be more common than building from tar files these days. Also, `configure` is rarely regenerated so it wouldn't be much trouble to us to have it in git. Or would it? 

I trust your judgment. If you are definitely opposed to bending the rules, let me know and I will close the issue. Thanks!

**Comment by astrand** [comment]
https://stackoverflow.com/questions/15745534/should-i-include-configure-and-makefile-in-a-github-repository/41360302 seems to contain good information. I agree that building directly from Git is now common, but I think people should also be used to having to run bootstrap or autoreconf. So although I can accept bending the rules if you really want, my suggestion is still to avoid committing generated files such as configure.

**Comment by hackerb9** [comment]
Including configure in a github _release_, not source, as suggested by the answer you linked to, makes sense to me.
