### ISSUE TITLE
patch to support the TIMESTAMP target

### ISSUE THREAD

**Issue by astrand** [astrand/xclip#9]
Greetings, esteemed masters of the X11 clipboard.  I offer a patch to offer half-baked nominal compliance with the end of ICCCM section 2.6.2, which instructs: "selection owners must support conversion to TIMESTAMP, returning the timestamp they used to obtain the selection".

At some point between icaclient_13.0.0.256735_amd64.deb and icaclient_13.1.0.285639_amd64.deb, Citrix Receiver for Linux began demanding that the selection owner respond to queries for the TIMESTAMP target.  If a response isn't forthcoming, it refuses to transfer the selection to the Windows box on the other end of its connection.  This sort of tedious requirement isn't apparently restricted to this commercial software, as https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=584686 demonstrates the same behavior with rdesktop, remedied a few years ago.  http://lists.freedesktop.org/archives/spice-devel/2014-July/017102.html suggests that some version of VNC might have a similar requirement, so perhaps it isn't even restricted to protocols for accessing Windows remotely.

I started out wanting to paste to Windows from Google Chrome and from various Java applications.  Neither of these serve the TIMESTAMP target, Google Chrome seemingly since its switch to the "Aura" toolkit.  I plan to raise RFEs on both, but it was xclip that gave me an understanding of what was wrong.  It was xclip that gave me a work-around - with the patched version I can leave this running and I'm sorted:

while true; do xclip -o | xclip -i; done &

And I suspect it will be xclip that will be most receptive to my RFE.  "But you say it's half-baked".  Sadly so.  I return CurrentTime for this TIMESTAMP query.  This is consistent with what xclip already passes to XSetSelection, with a FIXME about ICCCM compliance.  It does enough to rescue me from the icaclient version that I'll need if I'm to upgrade from Debian Wheezy to Debian Jessie.  I submit that it's a small step in the right direction.

Reported by: mdorey

Original Ticket: [xclip/patches/7](https://sourceforge.net/p/xclip/patches/7)

**Comment by hackerb9** [comment]
This should have been working for a while now. Pull #88 implements this "half-baked" solution, adding a variable (`ownertime`)which is currently just set to CurrentTime. I've also filed bug #92 for a fully baked solution.
